id = "hybrid-theme"
name = "hybrid"
version = "0.1.0"
schema_version = 1
authors = ["KAMIHARA Takumi <hello.camiha@email.com>"]
description = "hybrid theme for Zed. This is a port of the vim-hybrid theme."
repository = "https://github.com/camiha/zed-hybrid"